---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-cluster
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudnative-pg-app-secret
    template:
      data:
        password: '{{ .password }}'
        username: '{{ .username }}'
  dataFrom:
    - extract:
        key: cloudnative-pg-credentials-secret
