services:
  matchbox-init:
    image: alpine:latest
    container_name: matchbox-init
    entrypoint: sh
    command:
      - -c
      - |
        apk add --no-cache curl openssl bash
        /scripts/download-assets.sh
        /scripts/check-certs.sh
    volumes:
      - ../assets:/assets
      - ./certs:/certs
      - ./scripts:/scripts:ro

  matchbox:
    image: quay.io/poseidon/matchbox:v0.11.0
    container_name: matchbox
    restart: unless-stopped
    env_file:
      - certs.env
    command:
      - -address=0.0.0.0:8085
      - -rpc-address=0.0.0.0:8989
      - -log-level=debug
      - -cert-file=/etc/matchbox/cert/server.crt
      - -key-file=/etc/matchbox/cert/server.key
      - -ca-file=/etc/matchbox/cert/ca.crt
      - -assets-path=/var/lib/matchbox/assets
    volumes:
      - ./profiles:/var/lib/matchbox/profiles:ro
      - ./groups:/var/lib/matchbox/groups:ro
      - ../assets:/var/lib/matchbox/assets:ro
      - ./certs/server.crt:/etc/matchbox/cert/server.crt:ro
      - ./certs/server.key:/etc/matchbox/cert/server.key:ro
      - ./certs/ca.crt:/etc/matchbox/cert/ca.crt:ro
    ports:
      - "8085:8085/tcp"
      - "8989:8989/tcp"
    dns:
      - 192.168.1.3
    dns_search: lan
    depends_on:
      matchbox-init:
        condition: service_completed_successfully
      adguard:
        condition: service_started
