---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: miroir-local
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: miroir-local
