---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}
spec:
  oidc:
    provider:
      issuer: "https://auth.${DOMAIN}/application/o/${APP}/"
      backendRefs:
        - group: ""
          kind: Service
          name: authentik-server
          namespace: security
          port: 80
    clientID: ${APP}
    clientSecret:
      name: ${APP}-oidc-secret
    scopes:
      - openid
      - email
      - profile
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
