---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: ${APP}-oidc-secret
    template:
      data:
        client-secret: "{{ .${APP} }}"
  dataFrom:
    - extract:
        key: oidc-client-secrets
