---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mongo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: unifi-mongo-secret
    template:
      data:
        MONGO_AUTHSOURCE: 'admin'
        MONGO_DBNAME: 'unifi'
        MONGO_INITDB_DATABASE: 'admin'
        MONGO_INITDB_ROOT_PASSWORD: '{{ .MONGO_INITDB_ROOT_PASSWORD }}'
        MONGO_INITDB_ROOT_USERNAME: '{{ .MONGO_INITDB_ROOT_USERNAME }}'
        MONGO_PASS: '{{ .MONGO_PASS }}'
        MONGO_USER: '{{ .MONGO_USER }}'
        prom-password: '{{ index . "prom-password" }}'
        prom-username: '{{ index . "prom-username" }}'
  dataFrom:
    - extract:
        key: unifi-mongo-credentials-secret
