---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: qbtools-secret
    template:
      data:
        config.yaml: '{{ .config.yaml }}'
  dataFrom:
    - extract:
        key: qbittorrent-tools-secret
