---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      tqm:
        type: cronjob
        cronjob:
          schedule: '@hourly'
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        pod:
          restartPolicy: OnFailure
          securityContext: &podSecurityContext
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
        initContainers:
          retag:
            image: &tqm-image
              repository: ghcr.io/home-operations/tqm
              tag: 1.19.0
            args:
              - retag
              - qb
            resources: &resources
              requests:
                memory: 128Mi
                cpu: 25m
              limits:
                memory: 256Mi
            securityContext: &containerSecurityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
        containers:
          app:
            image: *tqm-image
            args:
              - clean
              - qb
              # - --dry-run
            resources: *resources
            securityContext: *containerSecurityContext
      qbrr:
        pod:
          securityContext: *podSecurityContext
        containers:
          app:
            image:
              repository: ghcr.io/buroa/qbrr
              tag: 0.1.6
            env:
              QBITTORRENT_HOST: http://qbittorrent.downloads.svc.cluster.local:8080
            resources: *resources
            securityContext: *containerSecurityContext
    persistence:
      config-file:
        type: secret
        name: qbtools-secret
        advancedMounts:
          tqm:
            retag:
              - path: /.config/tqm/config.yaml
                subPath: config
                readOnly: true
            app:
              - path: /.config/tqm/config.yaml
                subPath: config
                readOnly: true
