---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: alertmanager-secret
    template:
      data:
        PUSHOVER_API_TOKEN: '{{ .PUSHOVER_API_TOKEN }}'
        PUSHOVER_API_USERKEY: '{{ .PUSHOVER_API_USERKEY }}'
  dataFrom:
    - extract:
        key: kube-prometheus-stack-secret
