---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: jellyseerr-secret
    template:
      data:
        DB_HOST: 'cluster18-rw.database.svc.cluster.local'
        DB_NAME: 'jellyseerr'
        DB_PASS: '{{ .DB_PASS }}'
        DB_PORT: "5432"
        DB_TYPE: 'postgres'
        DB_USER: '{{ .DB_USER }}'
        INIT_POSTGRES_DBNAME: 'jellyseerr'
        INIT_POSTGRES_HOST: 'cluster18-rw.database.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .DB_PASS }}'
        INIT_POSTGRES_PASS_ENCODED: '{{ .INIT_POSTGRES_PASS_ENCODED }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .DB_USER }}'
  dataFrom:
    - extract:
        key: jellyseerr-secret
    - extract:
        key: postgres-superuser-secret
