---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: home-assistant-dashboards
    files:
      - dashboards/overview.yaml
      - dashboards/energy.yaml
      - dashboards/hvac.yaml
      - dashboards/security.yaml
      - dashboards/outlets.yaml
    options:
      disableNameSuffixHash: true
