---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/persistentvolumeclaim-v1.json
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-cache
  namespace: home
spec:
  storageClassName: miroir-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
