---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app readarr
  namespace: &namespace downloads
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/ext-auth
  interval: 1h
  path: "./kubernetes/apps/downloads/readarr/app"
  dependsOn:
    - name: external-secrets-store
      namespace: security
    - name: authentik
      namespace: security
    - name: cloudnative-pg-cluster
      namespace: database
    - name: volsync
      namespace: storage
    - name: common-pvc
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      CACHE_CAPACITY: 2Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
