# WireGuard VPN — server + peers

resource "opnsense_wireguard_server" "wg0" {
  name           = "wg0"
  port           = local.wireguard.port
  tunnel_address = [local.wireguard.address]
  private_key    = var.wg_private_key
  public_key     = "" # Generated by OPNsense from private key
  enabled        = true
}

resource "opnsense_wireguard_client" "peer" {
  for_each = {
    for peer in local.wireguard.peers : peer.name => peer
  }

  name           = each.value.name
  public_key     = var.wg_peer_public_keys[each.key]
  tunnel_address = [each.value.allowed_ips]
  keep_alive     = each.value.persistent_keepalive
  enabled        = true
}
