---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: nut-exporter
    template:
      data:
        NUT_EXPORTER_USERNAME: slaveuser
        NUT_EXPORTER_PASSWORD: '{{ .value }}'
  dataFrom:
    - extract:
        key: 07518fe9-65db-4960-95cc-b3f00157d8fa
