---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# Access control policies
version: 1
entries:
  - model: authentik_policies_expression.expressionpolicy
    identifiers:
      name: require-users-group
    attrs:
      expression: |
        return ak_is_group_member(request.user, name="users")
