# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:a+uw28wzHU0ltjMMfNsLWrtNDefw6I00D6QsmKBltzU=,iv:DEn2Gh5IKXtEPqflbURywU0+WCyxtb5hQKCCvo628nY=,tag:RD6pkyx9Y/XTckxqBCfDcg==,type:str]
sops:
  age:
    - recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsKzk3SDZqclFwZUFFT3hW
        QzhvSlg1YnplWm1UcW9Jb3NrV1FKQjlYajFVCmZkTU5GMFBSTUc0UkZHVUh3azlY
        eUk2TTd3MEFUN2lrN2Ezc01UZEhzQjQKLS0tIGFDTzJYc0ZjK3pvTWNSWXNRcE4y
        OXp5WktjcjRuNEd3emNGdVZrRitGUUUK9bMjEv4RQXV4Ffut0b8xcB4dgPs3CC8k
        DBJsqCfJFFMsaNHbIixqeLn8lUCseyXptIB5O5y76VX9bK/gSKuL/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T18:34:17Z"
  mac: ENC[AES256_GCM,data:KSK6dAV5XdxymjvWTFWECCt+Z9zEv4CI3oYkcmJ9zgpu5FbQ5/p2IxapZVjPIUqrf+Ag99eyoTG4nIvOhJx5f4PhjFRip3twNnC/b47WUoAcPjYFTx02+Uv4AugmGVbo6qMDC0FJf4TB4tOBzLrzbLMNjqxhVYo9rARLOmUGTe4=,iv:vsjoHIA3dx2mt/6glyVrV2eR1lQU/LakI2hR7741Ncw=,tag:F49/TIGe1XmAUmvTMQJimw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
