---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app esp-home
  namespace: &namespace home
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur
    - ../../../../components/oidc-auth
  interval: 1h
  path: "./kubernetes/apps/home/esp-home/app"
  dependsOn:
    - name: miroir-config
      namespace: miroir-system
    - name: kopiur-repository
      namespace: volsync-system
    - name: authelia
      namespace: security
  postBuild:
    substitute:
      APP: *app
      OIDC_ROUTE: *app
      KOPIUR_CAPACITY: 2Gi
      CRON_EXPRESSION: '15 1 * * *'
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
