---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: prowlarr-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: 'prowlarr prowlarr_log'
        INIT_POSTGRES_HOST: 'cluster18-rw.database.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .PROWLARR__POSTGRES__PASSWORD }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .PROWLARR__POSTGRES__USER }}'
        PROWLARR__API__KEY: '{{ .PROWLARR__API__KEY }}'
        PROWLARR__AUTH__APIKEY: '{{ .PROWLARR__AUTH__APIKEY }}'
        PROWLARR__POSTGRES__HOST: 'cluster18-rw.database.svc.cluster.local'
        PROWLARR__POSTGRES__LOGDB: 'prowlarr_log'
        PROWLARR__POSTGRES__MAINDB: 'prowlarr'
        PROWLARR__POSTGRES__PASSWORD: '{{ .PROWLARR__POSTGRES__PASSWORD }}'
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: '{{ .PROWLARR__POSTGRES__USER }}'
  dataFrom:
    - extract:
        key: prowlarr-secret
    - extract:
        key: postgres-superuser-secret
