---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kavita
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      kavita:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          perm-fix:
            image:
              repository: busybox
              tag: latest
            command: ['sh', '-c', "chown -R 1000:568 /kavita/config && chmod -R 775 /kavita/config"]
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.8.8@sha256:22c42f3cc83fb98b98a6d6336200b615faf2cfd2db22dab363136744efda1bb0
            env:
              TZ: Europe/Rome
            resources:
              requests:
                cpu: 15m
                memory: 64Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        # runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 5000
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Kavita
          gethomepage.dev/group: Media
          gethomepage.dev/icon: kavita.png
          gethomepage.dev/description: Comic/Ebook Web Reader
          gethomepage.dev/widget.type: kavita
          gethomepage.dev/widget.url: https://comics.${DOMAIN}
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_KAVITA_USERNAME}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_KAVITA_PASSWORD}}` }}"
        hostnames:
          - comics.${DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /kavita/config
      media:
        existingClaim: nas-media-media
        globalMounts:
          - path: /media
