#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$INFRA_DIR/.." && pwd)"

source "$ROOT_DIR/.env"

SECRETS_FILE="$INFRA_DIR/secrets.auto.tfvars"

echo "Resolving secrets from Bitwarden Secrets Manager..."

bws_get() { bws secret get "$1" | jq -r '.value'; }

# BWS secret UUIDs
MATRYOSHKA_CREDS="f26804d7-0421-4fc5-8902-b42e0076c953" # gitleaks:allow
GLADOS_API="c1646567-edf2-4f42-88f7-b42e0077b19e" # gitleaks:allow
GLADOS_WG_SERVER="ff9b6ce0-a0ea-40a2-8a08-b427014bd44e" # gitleaks:allow
GLADOS_WG_PEERS="9a54aa5f-5829-49b3-9b61-b42e007920b5" # gitleaks:allow
CF_SECRET="914ca867-e673-4d3b-9e7c-b3eb008ba0d9" # gitleaks:allow
BASE_DOMAIN="88234b63-9f5f-4a52-88ba-b42b00fde831" # gitleaks:allow

cat > "$SECRETS_FILE" <<EOF
# Auto-generated by sync-secrets.sh — DO NOT COMMIT
# Re-run this script after rotating secrets

proxmox_username     = "$(bws_get "$MATRYOSHKA_CREDS" | jq -r '.username')"
proxmox_password     = "$(bws_get "$MATRYOSHKA_CREDS" | jq -r '.password')"
opnsense_api_key     = "$(bws_get "$GLADOS_API" | jq -r '.key')"
opnsense_api_secret  = "$(bws_get "$GLADOS_API" | jq -r '.secret')"
wg_private_key       = "$(bws_get "$GLADOS_WG_SERVER" | jq -r '.private')"
wg_public_key        = "$(bws_get "$GLADOS_WG_SERVER" | jq -r '.public')"
cloudflare_api_token = "$(bws_get "$CF_SECRET" | jq -r '.CF_API_TOKEN')"
base_domain          = "$(bws_get "$BASE_DOMAIN")"

wg_peer_public_keys = {
  matteo-mac     = "$(bws_get "$GLADOS_WG_PEERS" | jq -r '.[] | select(.name == "matteo-mac") | .public')"
  matteo-iphone  = "$(bws_get "$GLADOS_WG_PEERS" | jq -r '.[] | select(.name == "matteo-iphone") | .public')"
  matteo-retroid = "$(bws_get "$GLADOS_WG_PEERS" | jq -r '.[] | select(.name == "matteo-retroid") | .public')"
}
EOF

echo "Secrets written to $SECRETS_FILE"
