#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$INFRA_DIR/.." && pwd)"

source "$ROOT_DIR/.env"

SECRETS_FILE="$INFRA_DIR/secrets.auto.tfvars"

echo "Resolving secrets from Bitwarden Secrets Manager..."

bws_get() { bws secret get "$1" | jq -r '.value'; }
bws_get_key() { bws secret get "$1" | jq -r ".value | fromjson | .$2"; }

cat > "$SECRETS_FILE" <<EOF
# Auto-generated by sync-secrets.sh — DO NOT COMMIT
# Re-run this script after rotating secrets

proxmox_api_token    = "$(bws_get "PLACEHOLDER_PROXMOX_API_TOKEN")"
opnsense_api_key     = "$(bws_get "PLACEHOLDER_OPNSENSE_API_KEY")"
opnsense_api_secret  = "$(bws_get "PLACEHOLDER_OPNSENSE_API_SECRET")"
wg_private_key       = "$(bws_get "ff9b6ce0-a0ea-40a2-8a08-b427014bd44e")"
cloudflare_api_token = "$(bws_get_key "914ca867-e673-4d3b-9e7c-b3eb008ba0d9" ".CF_API_TOKEN")"
base_domain          = "$(bws_get "88234b63-9f5f-4a52-88ba-b42b00fde831")"

wg_peer_public_keys = {
  matteo-mac    = "$(bws_get "74e29b40-4a3a-45d2-8973-b427014bd553")"
  matteo-iphone = "$(bws_get "2b832c89-99b7-43d8-8dc6-b427014bd6b8")"
}
EOF

echo "Secrets written to $SECRETS_FILE"
