---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-immich-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudnative-immich-user
    template:
      data:
        password: '{{ .password }}'
        username: '{{ .username }}'
  dataFrom:
    - extract:
        key: cloudnative-immich-user-secret
