---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: garage-s3
    template:
      data:
        aws-access-key-id: '{{ .GARAGE_S3_ACCESS_KEY_ID }}'
        aws-secret-access-key: '{{ .GARAGE_S3_SECRET_KEY }}'
  data:
    - secretKey: GARAGE_S3_ACCESS_KEY_ID
      remoteRef:
        key: GARAGE_S3_ACCESS_KEY_ID
    - secretKey: GARAGE_S3_SECRET_KEY
      remoteRef:
        key: GARAGE_S3_SECRET_KEY
