---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: paperless-secrets
    template:
      data:
        INIT_POSTGRES_DBNAME: 'paperless'
        INIT_POSTGRES_HOST: 'cluster18-rw.database.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .PAPERLESS_DBPASS }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .PAPERLESS_DBUSER }}'
        PAPERLESS_ADMIN_PASSWORD: '{{ .PAPERLESS_ADMIN_PASSWORD }}'
        PAPERLESS_ADMIN_USER: '{{ .PAPERLESS_ADMIN_USER }}'
        PAPERLESS_ADMIN_MAIL: '{{ .PAPERLESS_ADMIN_MAIL }}'
        PAPERLESS_DBENGINE: 'postgres'
        PAPERLESS_DBHOST: 'cluster18-rw.database.svc.cluster.local'
        PAPERLESS_DBNAME: 'paperless'
        PAPERLESS_DBPASS: '{{ .PAPERLESS_DBPASS }}'
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBUSER: '{{ .PAPERLESS_DBUSER }}'
        PAPERLESS_SECRET_KEY: '{{ .PAPERLESS_SECRET_KEY }}'
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "paperless",
                  "secret": "{{ .PAPERLESS_OAUTH_CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://auth.${DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": true
            }
          }
  dataFrom:
    - extract:
        key: paperless-secret
    - extract:
        key: postgres-superuser-secret
    - extract:
        key: authentik-secret
