---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peekaboo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      peekaboo:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/adumat/peekaboo
              tag: "0.7.0"
            env:
              PEEKABOO_CONFIG: /config/config.yaml
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet: { path: /healthz, port: &port 3000 }
                  periodSeconds: 10
              readiness: *probes
            resources:
              requests: { cpu: 50m, memory: 96Mi }
              limits: { memory: 256Mi }
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http: { port: *port }
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Peekaboo
          gethomepage.dev/description: Baby monitor
        hostnames: ["peekaboo.${DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs: [{ identifier: app, port: *port }]
    persistence:
      config:
        type: configMap
        name: peekaboo-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
