---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_ADGUARD_USERNAME: '{{ .ADGUARD_USERNAME }}'
        HOMEPAGE_VAR_ADGUARD_PASSWORD: '{{ .ADGUARD_PASSWORD }}'
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: '{{ .HOMEPAGE_VAR_AUTHENTIK_TOKEN }}'
        HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: '{{ .HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN }}'
        HOMEPAGE_VAR_AUTOBRR_TOKEN: '{{ .HOMEPAGE_VAR_AUTOBRR_TOKEN }}'
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: '{{ .HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID }}'
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: '{{ .HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN }}'
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: '{{ .HOMEPAGE_VAR_CLOUDFLARED_TUNNELID }}'
        HOMEPAGE_VAR_GRAFANA_PASSWORD: '{{ .HOMEPAGE_VAR_GRAFANA_PASSWORD }}'
        HOMEPAGE_VAR_GRAFANA_USERNAME: '{{ .HOMEPAGE_VAR_GRAFANA_USERNAME }}'
        HOMEPAGE_VAR_HASS_TOKEN: '{{ .HOMEPAGE_VAR_HASS_TOKEN }}'
        HOMEPAGE_VAR_IMMICH_API_KEY: '{{ .HOMEPAGE_VAR_IMMICH_API_KEY }}'
        HOMEPAGE_VAR_JELLYFIN_TOKEN: '{{ .HOMEPAGE_VAR_JELLYFIN_TOKEN }}'
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: '{{ .HOMEPAGE_VAR_JELLYSEERR_TOKEN }}'
        HOMEPAGE_VAR_KAPOWARR_TOKEN: '{{ .HOMEPAGE_VAR_KAPOWARR_TOKEN }}'
        HOMEPAGE_VAR_KAVITA_PASSWORD: '{{ .HOMEPAGE_VAR_KAVITA_PASSWORD }}'
        HOMEPAGE_VAR_KAVITA_USERNAME: '{{ .HOMEPAGE_VAR_KAVITA_USERNAME }}'
        HOMEPAGE_VAR_LATITUDE: '{{ .HOMEPAGE_VAR_LATITUDE }}'
        HOMEPAGE_VAR_LONGITUDE: '{{ .HOMEPAGE_VAR_LONGITUDE }}'
        HOMEPAGE_VAR_MINIFLUX_API_KEY: '{{ .HOMEPAGE_VAR_MINIFLUX_API_KEY }}'
        HOMEPAGE_VAR_PAPERLESS_TOKEN: '{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}'
        HOMEPAGE_VAR_PROWLARR_TOKEN: '{{ .HOMEPAGE_VAR_PROWLARR_TOKEN }}'
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: '{{ .HOMEPAGE_VAR_QBITTORRENT_PASSWORD }}'
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: '{{ .HOMEPAGE_VAR_QBITTORRENT_USERNAME }}'
        HOMEPAGE_VAR_RADARR_TOKEN: '{{ .HOMEPAGE_VAR_RADARR_TOKEN }}'
        HOMEPAGE_VAR_READARR_TOKEN: '{{ .HOMEPAGE_VAR_READARR_TOKEN }}'
        HOMEPAGE_VAR_SONARR_TOKEN: '{{ .HOMEPAGE_VAR_SONARR_TOKEN }}'
        HOMEPAGE_VAR_UNIFI_PASSWORD: '{{ .HOMEPAGE_VAR_UNIFI_PASSWORD }}'
        HOMEPAGE_VAR_UNIFI_USERNAME: '{{ .HOMEPAGE_VAR_UNIFI_USERNAME }}'
        HOMEPAGE_VAR_UNRAID_APIKEY: '{{ .HOMEPAGE_VAR_UNRAID_APIKEY }}'
  dataFrom:
    - extract:
        key: homepage-secret
  data:
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: 168a0f24-0b00-4c2d-91bb-b3f0015782cd
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: 3f36ba39-1813-4da6-bda5-b3f1015859ec
