---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: '{{ .HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN }}'
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: '{{ .HOMEPAGE_VAR_AUTHENTIK_TOKEN }}'
        HOMEPAGE_VAR_BAZARR_TOKEN: '{{ .HOMEPAGE_VAR_BAZARR_TOKEN }}'
        HOMEPAGE_VAR_CALIBRE_PASSWORD: '{{ .HOMEPAGE_VAR_CALIBRE_PASSWORD }}'
        HOMEPAGE_VAR_CALIBRE_USERNAME: '{{ .HOMEPAGE_VAR_CALIBRE_USERNAME }}'
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: '{{ .HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID }}'
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: '{{ .HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN }}'
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: '{{ .HOMEPAGE_VAR_CLOUDFLARED_TUNNELID }}'
        HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_URL: '{{ .HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_URL }}'
        HOMEPAGE_VAR_GRAFANA_PASSWORD: '{{ .HOMEPAGE_VAR_GRAFANA_PASSWORD }}'
        HOMEPAGE_VAR_GRAFANA_USERNAME: '{{ .HOMEPAGE_VAR_GRAFANA_USERNAME }}'
        HOMEPAGE_VAR_HASS_TOKEN: '{{ .HOMEPAGE_VAR_HASS_TOKEN }}'
        HOMEPAGE_VAR_HOMEASSISTANT_KEY: '{{ .HOMEPAGE_VAR_HOMEASSISTANT_KEY }}'
        HOMEPAGE_VAR_IMMICH_API_KEY: '{{ .HOMEPAGE_VAR_IMMICH_API_KEY }}'
        HOMEPAGE_VAR_JELLYFIN_TOKEN: '{{ .HOMEPAGE_VAR_JELLYFIN_TOKEN }}'
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: '{{ .HOMEPAGE_VAR_JELLYSEERR_TOKEN }}'
        HOMEPAGE_VAR_KAPOWARR_TOKEN: '{{ .HOMEPAGE_VAR_KAPOWARR_TOKEN }}'
        HOMEPAGE_VAR_KAVITA_PASSWORD: '{{ .HOMEPAGE_VAR_KAVITA_PASSWORD }}'
        HOMEPAGE_VAR_KAVITA_USERNAME: '{{ .HOMEPAGE_VAR_KAVITA_USERNAME }}'
        HOMEPAGE_VAR_KOMGA_PASSWORD: '{{ .HOMEPAGE_VAR_KOMGA_PASSWORD }}'
        HOMEPAGE_VAR_KOMGA_USERNAME: '{{ .HOMEPAGE_VAR_KOMGA_USERNAME }}'
        HOMEPAGE_VAR_LATITUDE: '{{ .HOMEPAGE_VAR_LATITUDE }}'
        HOMEPAGE_VAR_LONGITUDE: '{{ .HOMEPAGE_VAR_LONGITUDE }}'
        HOMEPAGE_VAR_LUBELOG_PASSWORD: '{{ .HOMEPAGE_VAR_LUBELOG_PASSWORD }}'
        HOMEPAGE_VAR_LUBELOG_USERNAME: '{{ .HOMEPAGE_VAR_LUBELOG_USERNAME }}'
        HOMEPAGE_VAR_MEALIE_API_KEY: '{{ .HOMEPAGE_VAR_MEALIE_API_KEY }}'
        HOMEPAGE_VAR_MINIFLUX_API_KEY: '{{ .HOMEPAGE_VAR_MINIFLUX_API_KEY }}'
        HOMEPAGE_VAR_OPNSENSE_PASSWORD: '{{ .HOMEPAGE_VAR_OPNSENSE_PASSWORD }}'
        HOMEPAGE_VAR_OPNSENSE_USERNAME: '{{ .HOMEPAGE_VAR_OPNSENSE_USERNAME }}'
        HOMEPAGE_VAR_OVERSEERR_TOKEN: '{{ .HOMEPAGE_VAR_OVERSEERR_TOKEN }}'
        HOMEPAGE_VAR_PAPERLESS_TOKEN: '{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}'
        HOMEPAGE_VAR_PIHOLE_API_KEY: '{{ .HOMEPAGE_VAR_PIHOLE_API_KEY }}'
        HOMEPAGE_VAR_PLANTIT_API_KEY: '{{ .HOMEPAGE_VAR_PLANTIT_API_KEY }}'
        HOMEPAGE_VAR_PLEX_TOKEN: '{{ .HOMEPAGE_VAR_PLEX_TOKEN }}'
        HOMEPAGE_VAR_PROWLARR_TOKEN: '{{ .HOMEPAGE_VAR_PROWLARR_TOKEN }}'
        HOMEPAGE_VAR_PROXMOX_API_USER: '{{ .HOMEPAGE_VAR_PROXMOX_API_USER }}'
        HOMEPAGE_VAR_PROXMOX_API_USER_KEY: '{{ .HOMEPAGE_VAR_PROXMOX_API_USER_KEY }}'
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: '{{ .HOMEPAGE_VAR_QBITTORRENT_PASSWORD }}'
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: '{{ .HOMEPAGE_VAR_QBITTORRENT_USERNAME }}'
        HOMEPAGE_VAR_RADARR_TOKEN: '{{ .HOMEPAGE_VAR_RADARR_TOKEN }}'
        HOMEPAGE_VAR_READARR_TOKEN: '{{ .HOMEPAGE_VAR_READARR_TOKEN }}'
        HOMEPAGE_VAR_SABNZBD_TOKEN: '{{ .HOMEPAGE_VAR_SABNZBD_TOKEN }}'
        HOMEPAGE_VAR_SONARR_TOKEN: '{{ .HOMEPAGE_VAR_SONARR_TOKEN }}'
        HOMEPAGE_VAR_TANDOOR_API_KEY: '{{ .HOMEPAGE_VAR_TANDOOR_API_KEY }}'
        HOMEPAGE_VAR_TAUTULLI_TOKEN: '{{ .HOMEPAGE_VAR_TAUTULLI_TOKEN }}'
        HOMEPAGE_VAR_TRUENAS_APIKEY: '{{ .HOMEPAGE_VAR_TRUENAS_APIKEY }}'
        HOMEPAGE_VAR_UNIFI_PASSWORD: '{{ .HOMEPAGE_VAR_UNIFI_PASSWORD }}'
        HOMEPAGE_VAR_UNIFI_USERNAME: '{{ .HOMEPAGE_VAR_UNIFI_USERNAME }}'
  dataFrom:
    - extract:
        key: homepage-secret
