---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pyload-ng
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: pyload-ng-secret
    template:
      data:
        WIREGUARD_ADDRESSES: '{{ .WIREGUARD_ADDRESSES }}'
        WIREGUARD_PRIVATE_KEY: '{{ .WIREGUARD_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: pyload-ng-secret
