apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:L2eb2JT0pfs9Eg9YnkrqELRkN6wNzUjF6IdK+19YTXa1/hUFiN08hQ==,iv:sWBVQ19eU/DCwqYt6SelacYrII+ZHsMz0WPv2wXOFUw=,tag:v+FFyw5j1WdxNq5XznEKpg==,type:str]
sops:
    age:
        - recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSFVlZ3ZIbVRlZnpTbEJx
            NW5kZlhBSDNYYnRMQndHU21hTTdleVVJUG1jCnVMNm53eXdWZ1drN0x2UHZDNUMy
            b1B4bVJQRVBrVkgzYXQwdmFxelZSRVkKLS0tIDNWTjk1YmxXUFQ5QmFLRDVzOEFP
            Z1VYbUkzamV0RXZTZWc5SEJkc281WEkKCiV2GX1mplt/wUwvGxDPmIYpaKjmrsqU
            gp5H8Gfki5c5vzj0BfzQLELeLOEq9pjG8LY6UDp6obPlk4h9o003oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T07:09:08Z"
    mac: ENC[AES256_GCM,data:PJcrQXFW515Mrb+6111WcX5t5vTrRmQ6IcK554ofqj9G/CIUbyz5+zEsRyMfEAX+yd4lqlhFbJ6/SbUgYLIQwgCzdQMXghp0HAsBzIA8g01g3n7SzOkeG/zjEXYLUJQEz4divPLU5chWfcbXwDbUGO4ypkaWqth/c+e6LUG0hB4=,iv:GXQBL8+u1Bs1/tO7NiF9lfFVUcAlvWuN33BF9TBLMcI=,tag:qY+rUP64bO9r7f9IYU1N2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
