---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: miniflux-secret
    template:
      data:
        ADMIN_PASSWORD: '{{ .ADMIN_PASSWORD }}'
        ADMIN_USERNAME: '{{ .ADMIN_USERNAME }}'
        DATABASE_URL: '{{ .DATABASE_URL }}'
        DB_HOST: 'cluster17-rw.databases.svc.cluster.local'
        DB_NAME: 'miniflux'
        DB_PASS: '{{ .DB_PASS }}'
        DB_PORT: "5432"
        DB_TYPE: 'postgres'
        DB_USER: '{{ .DB_USER }}'
        INIT_POSTGRES_DBNAME: 'miniflux'
        INIT_POSTGRES_HOST: 'cluster17-rw.databases.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .DB_PASS }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .DB_USER }}'
  dataFrom:
    - extract:
        key: miniflux-secret
    - extract:
        key: postgres-superuser-secret
