services:
  doco-cd-donkey:
    image: ghcr.io/kimdre/doco-cd:0.103.0
    container_name: doco-cd-donkey
    restart: unless-stopped
    profiles: [donkey]
    environment:
      TZ: Europe/Rome
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      SECRET_PROVIDER: bitwarden_sm
      SECRET_PROVIDER_ACCESS_TOKEN: ${BWS_ACCESS_TOKEN}
      SECRET_PROVIDER_API_URL: https://vault.bitwarden.eu/api
      SECRET_PROVIDER_IDENTITY_URL: https://vault.bitwarden.eu/identity
      POLL_CONFIG_FILE: /config/poll.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - ./poll-donkey.yaml:/config/poll.yaml:ro
    healthcheck:
      test: ['CMD', '/doco-cd', 'healthcheck']
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

  doco-cd-elizabeth:
    image: ghcr.io/kimdre/doco-cd:0.103.0
    container_name: doco-cd-elizabeth
    restart: unless-stopped
    profiles: [elizabeth]
    environment:
      TZ: Europe/Rome
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      SECRET_PROVIDER: bitwarden_sm
      SECRET_PROVIDER_ACCESS_TOKEN: ${BWS_ACCESS_TOKEN}
      SECRET_PROVIDER_API_URL: https://vault.bitwarden.eu/api
      SECRET_PROVIDER_IDENTITY_URL: https://vault.bitwarden.eu/identity
      POLL_CONFIG_FILE: /config/poll.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - ./poll-elizabeth.yaml:/config/poll.yaml:ro
    healthcheck:
      test: ['CMD', '/doco-cd', 'healthcheck']
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

  doco-cd-navi:
    image: ghcr.io/kimdre/doco-cd:0.103.0
    container_name: doco-cd-navi
    restart: unless-stopped
    profiles: [navi]
    environment:
      TZ: Europe/Rome
      GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
      SECRET_PROVIDER: bitwarden_sm
      SECRET_PROVIDER_ACCESS_TOKEN: ${BWS_ACCESS_TOKEN}
      SECRET_PROVIDER_API_URL: https://vault.bitwarden.eu/api
      SECRET_PROVIDER_IDENTITY_URL: https://vault.bitwarden.eu/identity
      POLL_CONFIG_FILE: /config/poll.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - ./poll-navi.yaml:/config/poll.yaml:ro
    healthcheck:
      test: ['CMD', '/doco-cd', 'healthcheck']
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data:
