---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-adguard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: external-dns-adguard-secret
    template:
      data:
        ADGUARD_PASSWORD: '{{ .ADGUARD_PASSWORD }}'
        ADGUARD_URL: 'http://donkey.lan:8080'
        ADGUARD_USER: '{{ .ADGUARD_USER }}'
  dataFrom:
    - extract:
        key: external-dns-adguard-secret
