services:
  chrony:
    image: ghcr.io/dockur/chrony:4.6.1
    container_name: chrony
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - NTP_SERVERS=0.it.pool.ntp.org,1.it.pool.ntp.org,2.it.pool.ntp.org,3.it.pool.ntp.org
    ports:
      - '123:123/udp'
    dns:
      - 192.168.1.3
    dns_search: lan
