---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: atuin-secrets
    template:
      data:
        ATUIN_DB_PASSWORD: '{{ .ATUIN_DB_PASSWORD }}'
        ATUIN_DB_URI: '{{ .ATUIN_DB_URI }}'
        ATUIN_DB_USERNAME: '{{ .ATUIN_DB_USERNAME }}'
        INIT_POSTGRES_DBNAME: 'atuin'
        INIT_POSTGRES_HOST: 'cluster17-rw.databases.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .ATUIN_DB_PASSWORD }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .ATUIN_DB_USERNAME }}'
  dataFrom:
    - extract:
        key: atuin-secret
    - extract:
        key: postgres-superuser-secret
