---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app capacitor
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      capacitor:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.4.8
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
        serviceAccount:
          identifier: *app
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9000
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Observability
          gethomepage.dev/name: Capacitor
          gethomepage.dev/icon: flux-cd.png
          gethomepage.dev/description: Flux CD Dashboard
        hostnames:
          - capacitor.${DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    serviceAccount:
      capacitor: {}
    rbac:
      roles:
        capacitor:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - events
                - namespaces
                - pods
                - services
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - source.toolkit.fluxcd.io
              resources:
                - gitrepositories
                - ocirepositories
                - helmrepositories
                - helmcharts
                - buckets
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - kustomize.toolkit.fluxcd.io
              resources:
                - kustomizations
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - helm.toolkit.fluxcd.io
              resources:
                - helmreleases
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - notification.toolkit.fluxcd.io
              resources:
                - alerts
                - providers
                - receivers
              verbs:
                - get
                - list
                - watch
      bindings:
        capacitor:
          type: ClusterRoleBinding
          roleRef:
            identifier: *app
          subjects:
            - identifier: *app
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
