---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: mosquitto-secret
    template:
      data:
        MQTT_USER_1: '{{ .zigbee2mqtt_username }}'
        MQTT_PASS_1: '{{ .zigbee2mqtt_password }}'
        MQTT_USER_2: '{{ .frigate_username }}'
        MQTT_PASS_2: '{{ .frigate_password }}'
        MQTT_USER_3: '{{ .homeassistant_username }}'
        MQTT_PASS_3: '{{ .homeassistant_password }}'
        MQTT_USER_4: '{{ .digiplex2mqtt_username }}'
        MQTT_PASS_4: '{{ .digiplex2mqtt_password }}'
  dataFrom:
    - extract:
        key: mqtt-zigbee2mqtt-secret
      rewrite:
        - regexp:
            source: (.*)
            target: zigbee2mqtt_$1
    - extract:
        key: mqtt-frigate-secret
      rewrite:
        - regexp:
            source: (.*)
            target: frigate_$1
    - extract:
        key: mqtt-homeassistant-secret
      rewrite:
        - regexp:
            source: (.*)
            target: homeassistant_$1
    - extract:
        key: mqtt-digiplex2mqtt-secret
      rewrite:
        - regexp:
            source: (.*)
            target: digiplex2mqtt_$1
