---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: karakeep-secrets
    template:
      data:
        MEILI_ADDR: 'http://karakeep-meilisearch.services.svc.cluster.local:7700'
        MEILI_MASTER_KEY: '{{ .MEILI_MASTER_KEY }}'
        NEXTAUTH_SECRET: '{{ .NEXTAUTH_SECRET }}'
        NEXTAUTH_URL: 'https://karakeep.${DOMAIN}'
        OAUTH_CLIENT_ID: 'karakeep'
        OAUTH_CLIENT_SECRET: '{{ (fromJson .oidc_raw).secret }}'
        OAUTH_WELLKNOWN_URL: 'https://auth.${DOMAIN}/.well-known/openid-configuration'
        OAUTH_PROVIDER_NAME: 'Authelia'
        OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: 'true'
        OPENAI_API_KEY: '{{ .LITELLM_MASTER_KEY }}'
  data:
    - secretKey: oidc_raw
      remoteRef:
        key: karakeep-oidc
  dataFrom:
    - extract:
        key: karakeep-secret
    - extract:
        key: litellm-secret
