---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: babymonitor-nginx
    files:
      - nginx.conf=./resources/nginx.conf
  - name: babymonitor-pwa
    files:
      - index.html=./resources/pwa/index.html
      - app.js=./resources/pwa/app.js
      - manifest.webmanifest=./resources/pwa/manifest.webmanifest
      - sw.js=./resources/pwa/sw.js
      - icon-192.png=./resources/pwa/icon-192.png
      - icon-512.png=./resources/pwa/icon-512.png
  - name: babymonitor-ffmpeg
    files:
      - ffmpeg-supervise.sh=./resources/ffmpeg-supervise.sh
generatorOptions:
  disableNameSuffixHash: true
