---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudnative-pg
    template:
      data:
        aws-access-key-id: '{{ index . "aws-access-key-id" }}'
        aws-secret-access-key: '{{ index . "aws-secret-access-key" }}'
  dataFrom:
    - extract:
        key: cloudnative-pg-backup-secret
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudnative-pg-secret
    template:
      data:
        username: '{{ .username }}'
        password: '{{ .password }}'
  dataFrom:
    - extract:
        key: cloudnative-pg-credentials-secret
