---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: zigbee2mqtt
    template:
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: '{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: '{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID }}'
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: '{{ .ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY }}'
        ZIGBEE2MQTT_CONFIG_MQTT_USER: '{{ .username }}'
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: '{{ .password }}'
  dataFrom:
    - extract:
        key: zigbee2mqtt-secret
    - extract:
        key: mqtt-zigbee2mqtt-secret
