---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - X-Forwarded-For # this is here so we can get the real IP
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - authorization
      - proxy-authorization
      - accept
      - cookie
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: authentik-server
          namespace: security
          port: 80
      path: /outpost.goauthentik.io/auth/envoy
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
