port=53053

bind-interfaces
domain=lan,192.168.1.0/24,local

# domain=internal
# dhcp-fqdn

# Set the DHCP server to authoritative mode. In this mode it will barge in
# and take over the lease for any client which broadcasts on the network,
# whether it has a record of the lease or not. This avoids long timeouts
# when a machine wakes up on a new network. DO NOT enable this if there's
# the slightest chance that you might end up accidentally configuring a DHCP
# server for your campus/company accidentally. The ISC server uses
# the same option, and this URL provides more information:
# http://www.isc.org/files/auth.html
dhcp-authoritative

# Log lots of extra information about DHCP transactions.
log-dhcp
log-queries

no-resolv
no-hosts

# Uncomment this to enable the integrated DHCP server, you need
# to supply the range of addresses available for lease and optionally
# a lease time. If you have more than one network, you will need to
# repeat this for each network on which you want to supply DHCP
# service.
dhcp-range=192.168.1.100,192.168.1.180,12h

# Enable dnsmasq's built-in TFTP server
enable-tftp

# Set the root directory for files available via FTP.
tftp-root=/var/ftpd

user=dnsmasq
group=dnsmasq

# Lease statici
host-record=elizabeth.lan,192.168.1.2
dhcp-host=14:DA:E9:4D:E7:65,elizabeth.lan,192.168.1.2
host-record=donkey.lan,192.168.1.3
dhcp-host=ee:33:32:65:7e:84,donkey.lan,192.168.1.3
host-record=switch-main.lan,192.168.1.10
dhcp-host=04:09:73:36:1B:A0,switch-main.lan,192.168.1.10
host-record=switch-living.lan,192.168.1.11
dhcp-host=D8:07:B6:D7:94:67,switch-living.lan,192.168.1.11
host-record=kube-nuc.lan,192.168.1.30
dhcp-host=1c:69:7a:a5:93:fc,kube-nuc.lan,192.168.1.30
host-record=kube-hp.lan,192.168.1.32
dhcp-host=f8:b4:6a:a5:87:ed,kube-hp.lan,192.168.1.32
host-record=kube-ceph-01.lan,192.168.1.33
dhcp-host=e8:6a:64:a4:89:ca,kube-ceph-01.lan,192.168.1.33
host-record=kube-ceph-02.lan,192.168.1.34
dhcp-host=e8:6a:64:f6:ff:af,kube-ceph-02.lan,192.168.1.34
host-record=kube-ceph-03.lan,192.168.1.35
dhcp-host=e8:6a:64:76:2a:18,kube-ceph-03.lan,192.168.1.35
host-record=cri-terme-euganee.lan,192.168.1.60
dhcp-host=e4:b9:7a:eb:57:90,cri-terme-euganee.lan,192.168.1.60
host-record=U6-PT.lan,192.168.1.50
dhcp-host=0c:ea:14:7c:1d:01,U6-PT.lan,192.168.1.50
host-record=U6-P1.lan,192.168.1.51
dhcp-host=0c:ea:14:7c:1f:51,U6-P1.lan,192.168.1.51
host-record=U6-EXT.lan,192.168.1.52
dhcp-host=d8:b3:70:e9:e0:82,U6-EXT.lan,192.168.1.52

# Lease riservati (nessuno attivo, esempio commentato)
# dhcp-host=d8:b3:70:e9:e0:82,U6-EXT.lan,192.168.1.52
# address=/U6-EXT.lan/192.168.1.52

# Extra address
host-record=k8s.clusterone.lan,192.168.1.40
host-record=k8s-gateway.clusterone.lan,192.168.1.41
host-record=internal.clusterone.lan,192.168.1.42
host-record=external.clusterone.lan,192.168.1.43
host-record=nut-server-room.lan,192.168.1.2

# gateway
dhcp-option=3,192.168.1.1

#dns
dhcp-option=6,192.168.1.3
dhcp-option=tag:nodns,6,8.8.8.8,8.8.4.4

dhcp-option=42,192.168.1.3
# unifi discover
dhcp-option=43,192.168.1.44

dhcp-mac=set:nodns,84:d6:c5:58:d9:b0

# Legacy PXE
dhcp-match=set:bios,option:client-arch,0
dhcp-boot=tag:bios,undionly.kpxe

# UEFI 32-bit
dhcp-match=set:efi32,option:client-arch,6
dhcp-boot=tag:efi32,ipxe.efi
# UEFI 64-bit
dhcp-match=set:efibc,option:client-arch,7
dhcp-boot=tag:efibc,ipxe.efi
dhcp-match=set:efi64,option:client-arch,9
dhcp-boot=tag:efi64,ipxe.efi

# iPXE - chainload to matchbox ipxe boot script
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://192.168.1.3:8085/boot.ipxe,192.168.1.3,192.168.1.3
# dhcp-boot=tag:ipxe,http://donkey.lan:8085/boot.ipxe,donkey.lan,donkey.lan
