services:
  dnsmasq:
    image: dockurr/dnsmasq:2.92
    container_name: dnsmasq
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ../assets:/var/ftpd:ro
    environment:
      - DNSMASQ_SHA=${dnsmasq_sha:-unknown}
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "echo | nc -w 2 127.0.0.1 53053"]
      interval: 10s
      timeout: 3s
      retries: 3

  dnsmasq-cache-flush:
    image: alpine:latest
    container_name: dnsmasq-cache-flush
    network_mode: "host"
    depends_on:
      dnsmasq:
        condition: service_healthy
    restart: "no"
    environment:
      - ADGUARD_USERNAME=${ADGUARD_USERNAME}
      - ADGUARD_PASSWORD=${ADGUARD_PASSWORD}
    command: sh -c "wget -q --post-data='' --user=$$ADGUARD_USERNAME --password=$$ADGUARD_PASSWORD http://localhost:8080/control/cache_clear -O /dev/null"
