---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: romm-secrets
    template:
      data:
        INIT_POSTGRES_DBNAME: "romm"
        INIT_POSTGRES_HOST: "cluster18-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .ROMM_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .ROMM_DB_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .INIT_POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
        DB_HOST: "cluster18-rw.database.svc.cluster.local"
        DB_PORT: "5432"
        DB_NAME: "romm"
        DB_USER: "{{ .ROMM_DB_USER }}"
        DB_PASSWD: "{{ .ROMM_DB_PASS }}"
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        OIDC_CLIENT_ID: "romm"
        OIDC_CLIENT_SECRET: "{{ .romm }}"
  dataFrom:
    - extract:
        key: romm-secret
    - extract:
        key: postgres-superuser-secret
    - extract:
        key: oidc-client-secrets
