---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.eu./api
      identityURL: https://vault.bitwarden.eu./identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: security
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: security
        key: tls.crt
      organizationID: ${SECRET_BITWARDEN_ORGANIZATION_ID}
      projectID: ${SECRET_BITWARDEN_PROJECT_ID}
