apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
stringData:
    token: ENC[AES256_GCM,data:0Ec1YOu7XL7q06wYFyRUv/+9uApkt5Y6uG6t7KmRbhp/HLXYPn6uH1upp7pjDT53VRQ2DNGb+TxOmVX+u+dQi5UuVY26IaUQ5cxXEMGvK+J9ShbKMv6+4tCqtS18RA==,iv:oid5U+rbo4Q1YLLHFdcsrPaaZtl2KuBMbqjSJ9pLhyM=,tag:bLOHZSMyMypIKcd2y346DQ==,type:str]
sops:
    age:
        - recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbVFxZEcrcUJhaUFSajFm
            Y2VESW5sZXlEWkJDM1Z1bzB4Y0lBSHp6Y0IwCnVIQm9wY2pqM3ZCMWdEWEp1aHl3
            Y0x0SlFsM1ZEU0dmR1ZrOXNwZ1pXOGsKLS0tIDk5dnp2QTA3dFpnaUhuTVUxZU95
            U0RzSkE5WU9CQzJVZTN5QjBSYTRNNzQKwghCUYj2Uu+j1NxamXJsLUpHuX1osxWP
            zSHPmyD1GPa50rDclfHKiKu/jnI6MLG+xhvx+H1wqjYAORWqr2h/zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:56:45Z"
    mac: ENC[AES256_GCM,data:68lhpzX0++9LNIcuylQr2GAvwUCYAW6Exp86DXIOmgxCv7nYIyjB58FNTPFBTF4PbFazFiYEwWyOrDVfPmuqWtDI7Rl/vLy/NKRx0rv8Ma2fxX7pXgYGdS8GyjhP6gFxstHPJVli5BY4BACe8H6GETd7AE1yyPTTVazOmYPWfDY=,iv:BgirxXUnRKqoVA7xJbQWH9FPSXSh6fMWvHuQezop0QU=,tag:wIrsNT0nL3HJmt9qN7TC9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
