---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: readarr-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: 'readarr readarr_log readarr_cache'
        INIT_POSTGRES_HOST: 'cluster17-rw.databases.svc.cluster.local'
        INIT_POSTGRES_PASS: '{{ .READARR__POSTGRES__PASSWORD }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .INIT_POSTGRES_SUPER_PASS }}'
        INIT_POSTGRES_SUPER_USER: '{{ .INIT_POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_USER: '{{ .READARR__POSTGRES__USER }}'
        READARR__API__KEY: '{{ .READARR__API__KEY }}'
        READARR__AUTH__APIKEY: '{{ .READARR__AUTH__APIKEY }}'
        READARR__POSTGRES__CACHEDB: 'readarr_cache'
        READARR__POSTGRES__HOST: 'cluster17-rw.databases.svc.cluster.local'
        READARR__POSTGRES__LOGDB: 'readarr_log'
        READARR__POSTGRES__MAINDB: 'readarr'
        READARR__POSTGRES__PASSWORD: '{{ .READARR__POSTGRES__PASSWORD }}'
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: '{{ .READARR__POSTGRES__USER }}'
  dataFrom:
    - extract:
        key: readarr-secret
    - extract:
        key: postgres-superuser-secret
