apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  EMAIL_ADDRESS_1: ENC[AES256_GCM,data:ncOIXBiVCXOvodW/pGovldYwWbk=,iv:UqALPrhD9GOI/yjThuCXAKQ5qP2/0Il4kCTdAGGilnY=,tag:S0p3NVu0FuAWsa4tTqvhqg==,type:str]
  DOMAIN: ENC[AES256_GCM,data:WgBgfk+2GI68,iv:CcFL72hGz04GtmegNTR9qMS720PJqiB+hEa7biN1B/g=,tag:SiGm/015kfGcuOQlPG3G1g==,type:str]
  LOCAL_DOMAIN: ENC[AES256_GCM,data:F0xzrHByDw3HlQ8pWbc=,iv:4CK1PjLHw7MEQJ8HudIVAljCu44tu6ANVh5uLA8ssvc=,tag:oCizjE37vhO0hUB/lBZicA==,type:str]
  SECRET_NAS_NAME: ENC[AES256_GCM,data:s3W4jgrqyy3meqQ54Q==,iv:qUeR3+3fMk4MyggkWdc6dDJaDgfnyjy4Qr1xygyHbNY=,tag:BNq0IzR3AaPX5X8JhQ3M5Q==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wG0vQO3Qp0lbyo2wphTgt4Y3dptztq/Iq+0Rno9RMuM68fZ6,iv:vEIoOYdCe+GjNHYpGZJqg/H/jDNga2kfM8hWm/2Iie4=,tag:O4aN1yTXFDDFV/YLZjcnTg==,type:str]
  SECRET_BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:9NOC2yJdNSiEqjOqH893mE3XJ6mSywEFvEdjir2S/vrQ5ylx,iv:ZpdydGr/aIRm4iQiFU9FDrb/N2Z5WVmj9iXkfJZ5bu8=,tag:7oT1JWdTb57ycvWRQ4lrwQ==,type:str]
  SECRET_BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:zkJaMaXlFNmv5mQ4DymNl80kuFy82BgPX+3rq0DYAtaZNEew,iv:NdBbqW+nL4nMCQhq2vcm1f9P3fN58gw2J5x7DrJnu2U=,tag:SaGRbbll/uvq02RfKxWHUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4allpRzlEdTRWa1ZoMG9t
        VzlsdjFTUTRaSmw0aHRUaXBxVURPVHJQOEI4CmxmYXMwN1JPQUtpMFNmUVdqb0Ra
        eDVlVGs1cm5hRnhIR1I2WDlJYnQ1S1EKLS0tIEx2bkM1OE1pNS9CWFlQL0xHZEpw
        ZDFZUmxIOHZSaEtOY2VtUlFHNkd6d00K3LRddVnpXHc88C/ncDpxHPo9BT9X2gEQ
        x/wMq30LeDvT+/hn2vmkHNhIm9Mu0aEGj5rcnaXeqWGQQu8/Ht+94Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-30T11:44:43Z"
  mac: ENC[AES256_GCM,data:vLbUeXhOsX+HVWYXRR9c9EX5NEeOqoV1CRvvQJmSHkj81Axt2l3AE7MWKW5sro4/b83ZR4qnuvC7OSOezXADph+J05fcrvAWUZ6mapOUL9T0Mb29yE/JV2ntOJ5O5a00rdAxVctgixB9Dlm5KKINajyd6uKdi4nI3Ck04TKUeXk=,iv:Ee1oEVvlncgYcswUKmLXIAhJmBxJUONXKP5D56BIHGQ=,tag:VF61YnhwOhTnYp38pbLd5w==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
