apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    EMAIL_ADDRESS_1: ENC[AES256_GCM,data:2ahNv9oajfLBeQXsl3y4o98QJSg=,iv:nK3DN1b+QCLgXGxpi+m/Zjn3z712BGCM0ZHV6fIR2io=,tag:o64bemhvaL0U2UUvWgk7Ww==,type:str]
    DOMAIN: ENC[AES256_GCM,data:u7s4ScSm1/bK,iv:m3Q9Ql1m+O8F0Supt2Xyqfj6C4n28cirip8yD5KgX34=,tag:ie9teFz1/zjGCtive66MIA==,type:str]
    LOCAL_DOMAIN: ENC[AES256_GCM,data:hyPzsca/JxlerIBbpcU=,iv:vQE0lRZgoZr7cmHHFCE2X1+6nqHHzv+u+tB3nVy4n+A=,tag:VzPoiR8PiGg08x5Q6gbPSw==,type:str]
    SECRET_NAS_NAME: ENC[AES256_GCM,data:OelNJmNeftYntvsaSQ==,iv:V3jkcuLWnmdoAxV3D2F0+pThzROlv5tvqDvU7Cdf/IM=,tag:jkGztfKnG+CMnGG2QvFGIQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XFarAbUw2T62Fi+cvolweWOzBVO6wUKsc/lw3tugoLeuvTIJ,iv:q4IQpHIn+zLi1rY6Y8xwmmYdBWi1qDfQJi86wyUan24=,tag:l/nXFOMScgHmbnKC+5y/kQ==,type:str]
    ROUTER_IP: ENC[AES256_GCM,data:m9msrgfemZaf+W4=,iv:Q/dGeOEX/WiVf4bJAzAbQPgj+KDiV6O3zdQlH7zaN50=,tag:mn+sf5BF4LGc1ldLXPzIvA==,type:str]
    SECRET_BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:5FFd3DrNtX6OSqLGU08d9VTKQyMTBzSwZz3oU9d4dSTjOxhB,iv:TMaXcATciVAvTtj3VPFZG/ASetmnuhlBLTrCdwZ6Ues=,tag:0lg2M3zDvCv4c254nizK+g==,type:str]
    SECRET_BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:EzQ8l3xGf2cZx7y9wWfrs7yB04Uda+al+7oovBidI0SiLhnt,iv:+W5TDhTSXxSJXDYrsTJjEWh8h11aG9BEcbMJo3uJv58=,tag:DjEaeyaaAVPibabfMBtWSQ==,type:str]
    MATTEO_EMAIL: ENC[AES256_GCM,data:ibGwfJk5unzEU5npnk2sLrOyyQw=,iv:heTtsLQNa3DVP717T+wk3VS05R+lO6VSmT1BwnvD+/M=,tag:8yGxX0gEovSh/kJ56dNM8g==,type:str]
    ELISA_EMAIL: ENC[AES256_GCM,data:GNOTZe1mtCCOlU7kpVStg0eMZeSzQaU=,iv:Wq7kusYTgFUsbnk9MhgYUjKbDtDe5kCQc0OmXNYG1DA=,tag:oX87h3JmRpBobjXR44SxCw==,type:str]
sops:
    age:
        - recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrd3UvYUZuRkltaytTcUx0
            RlV0VnF2N0hwenllTkdyY0VTUVN5SXFiR1hFCjhaK2E0SlNpaDE1WTVEU3RkQnpV
            Y1JXbWdCa3ZSVFBlNUdrZFJ6MDNtZkkKLS0tIFlObjQ5L0hhOUE5U2tpYXNFR0Nr
            RWhIeEdoN3dFdjg1VW80c2dwWm5FWTQKoWv3ak+A0eNn3jBcQVpEA1aH8LAWTnoi
            dE6v93CNO60ocuvuKEBmArSlA9kQ3+qYkpgWuOZVe9Mwm+l43mIe2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T22:15:04Z"
    mac: ENC[AES256_GCM,data:cxp9qRHzKhsaev2XBfYZqJGDwD5dHFmFUDs6maiwnlnBZjrrWpVmpqERSa2Hk8HCmdQ1TqHqE9ZGbO/5lyxT6mFq9Ai9sjfU+i2l5aps3FbTcELJ/kHZwZSCPVl9/frITIfwKVH/5ijypl+Li87Ua4i7y2YUc2hqKeYEoQpWcq4=,iv:vYvJiyULxL7E19OG42X6zX4yLCtEP48WYLezCjNdXJQ=,tag:hBAUCGAR1uJSB58i5+AbGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
