apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  EMAIL_ADDRESS_1: ENC[AES256_GCM,data:ncOIXBiVCXOvodW/pGovldYwWbk=,iv:UqALPrhD9GOI/yjThuCXAKQ5qP2/0Il4kCTdAGGilnY=,tag:S0p3NVu0FuAWsa4tTqvhqg==,type:str]
  DOMAIN: ENC[AES256_GCM,data:WgBgfk+2GI68,iv:CcFL72hGz04GtmegNTR9qMS720PJqiB+hEa7biN1B/g=,tag:SiGm/015kfGcuOQlPG3G1g==,type:str]
  LOCAL_DOMAIN: ENC[AES256_GCM,data:F0xzrHByDw3HlQ8pWbc=,iv:4CK1PjLHw7MEQJ8HudIVAljCu44tu6ANVh5uLA8ssvc=,tag:oCizjE37vhO0hUB/lBZicA==,type:str]
  SECRET_NAS_NAME: ENC[AES256_GCM,data:s3W4jgrqyy3meqQ54Q==,iv:qUeR3+3fMk4MyggkWdc6dDJaDgfnyjy4Qr1xygyHbNY=,tag:BNq0IzR3AaPX5X8JhQ3M5Q==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wG0vQO3Qp0lbyo2wphTgt4Y3dptztq/Iq+0Rno9RMuM68fZ6,iv:vEIoOYdCe+GjNHYpGZJqg/H/jDNga2kfM8hWm/2Iie4=,tag:O4aN1yTXFDDFV/YLZjcnTg==,type:str]
  SECRET_BITWARDEN_ORGANIZATION_ID: ENC[AES256_GCM,data:9NOC2yJdNSiEqjOqH893mE3XJ6mSywEFvEdjir2S/vrQ5ylx,iv:ZpdydGr/aIRm4iQiFU9FDrb/N2Z5WVmj9iXkfJZ5bu8=,tag:7oT1JWdTb57ycvWRQ4lrwQ==,type:str]
  SECRET_BITWARDEN_PROJECT_ID: ENC[AES256_GCM,data:zkJaMaXlFNmv5mQ4DymNl80kuFy82BgPX+3rq0DYAtaZNEew,iv:NdBbqW+nL4nMCQhq2vcm1f9P3fN58gw2J5x7DrJnu2U=,tag:SaGRbbll/uvq02RfKxWHUQ==,type:str]
  MATTEO_EMAIL: ENC[AES256_GCM,data:TL+JPtWQXlYKSyRgVm9GQ/SPEAc=,iv:ZuCeMDlnA/3fKa+LCYB2iejJoX+9TpLYmtTniXN7eX4=,tag:Hp9hN2uYNfBDox8C/Z5Mlg==,type:str]
  ELISA_EMAIL: ENC[AES256_GCM,data:xf9GWzVBB/7LM5GVcl6qFzcR6gb9Bf0=,iv:omzY3Bme+8u3Lr75W+eYdf762lcZnPqynMqDpLACn/Y=,tag:TL0XyDBw48uvinmKuUgsHA==,type:str]
sops:
  age:
    - recipient: age175fpp0mqvuhmfddz9f5gcvxaxv9x70mgrd0nfcnl2ypq2whckcsqtjds5v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4allpRzlEdTRWa1ZoMG9t
        VzlsdjFTUTRaSmw0aHRUaXBxVURPVHJQOEI4CmxmYXMwN1JPQUtpMFNmUVdqb0Ra
        eDVlVGs1cm5hRnhIR1I2WDlJYnQ1S1EKLS0tIEx2bkM1OE1pNS9CWFlQL0xHZEpw
        ZDFZUmxIOHZSaEtOY2VtUlFHNkd6d00K3LRddVnpXHc88C/ncDpxHPo9BT9X2gEQ
        x/wMq30LeDvT+/hn2vmkHNhIm9Mu0aEGj5rcnaXeqWGQQu8/Ht+94Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T08:36:31Z"
  mac: ENC[AES256_GCM,data:im/mhZ4fQrrgjcnPHeH6+dxL+awWEBKvkoYb2+ljRrXcc4INvDXcM7Hp9BulBGsosb5HTTWAwqNTB01x9dDHW5xmIHdWVEqLEywtMZReDZ+BsFuWUki7iqe6+fon/QzomB6vO3162I887psUuActxyvGxJo3/5wNx1oMr12EuS8=,iv:LdY4KR0xsRKeqUmyNmEvWsqAeYSeVrzZNNPrBQoTAkQ=,tag:AjxOdVDOhoAI2YYtaLLnBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
