---
api:
  listen: :80
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 192.168.1.46:8555
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478
streams:
  sofias-room:
    - rtsp://$${NVR_USERNAME}:$${NVR_PASSWORD}@192.168.1.156:554/stream1#backchannel=0
    - ffmpeg:sofias-room#audio=opus
  sofias-room_onvif:
    - onvif://$${NVR_USERNAME}:$${NVR_PASSWORD}@192.168.1.156:2020
  nicolos-room:
    - rtsp://$${NVR_USERNAME}:$${NVR_PASSWORD}@192.168.1.141:554/stream1#backchannel=0
    - ffmpeg:nicolos-room#audio=opus
  nicolos-room_onvif:
    - onvif://$${NVR_USERNAME}:$${NVR_PASSWORD}@192.168.1.141:2020
