---
api:
  listen: :80
rtsp:
  listen: :554
webrtc:
  listen: :8555
  candidates:
    - 10.1.11.6:8555
    - stun:8555
  ice_servers:
    - urls:
        - stun:stun.cloudflare.com:3478
streams:
  sofias-room:
    - rtsp://$${NVR_USERNAME}:$${NVR_PASSWORD}@sofia-camera.lan:554/stream1#backchannel=0
    - ffmpeg:sofias-room#audio=opus
  sofias-room_onvif:
    - onvif://$${NVR_USERNAME}:$${NVR_PASSWORD}@sofia-camera.lan:2020
  nicolos-room:
    - rtsp://$${NVR_USERNAME}:$${NVR_PASSWORD}@nicolo-camera.lan:554/stream1#backchannel=0
    - ffmpeg:nicolos-room#audio=opus
  nicolos-room_onvif:
    - onvif://$${NVR_USERNAME}:$${NVR_PASSWORD}@nicolo-camera.lan:2020
