---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: paperless-ai-secrets
    template:
      data:
        PAPERLESS_API_TOKEN: '{{ .PAPERLESS_API_TOKEN }}'
        CUSTOM_API_KEY: '{{ .LITELLM_MASTER_KEY }}'
  dataFrom:
    - extract:
        key: paperless-ai-secret
    - extract:
        key: litellm-secret
