#!/bin/bash
set -euo pipefail

# Paths inside the init container
DNSMASQ_CONF="/work/dnsmasq/dnsmasq.conf"
TALCONFIG="/work/talos/talconfig.yaml"
TALENV="/work/talos/talenv.yaml"
OUTPUT="/work/power-nap-over/config.yaml"
BIN_DIR="/work/power-nap-over/bin"

# Function to get MAC address from dnsmasq.conf for a given hostname
get_mac_from_dnsmasq() {
    local hostname="$1"
    grep "dhcp-host=.*${hostname}" "$DNSMASQ_CONF" | head -1 | cut -d',' -f1 | cut -d'=' -f2
}

# Parse talconfig.yaml to extract nodes
# Returns: hostname,ip,mac,controlPlane (true/false)
parse_talconfig() {
    yq eval '.nodes[] | [.hostname, .ipAddress, .networkInterfaces[0].deviceSelector.hardwareAddr, .controlPlane] | @csv' "$TALCONFIG" | tr -d '"'
}

# Download talosctl matching cluster version
download_talosctl() {
    local talos_version arch
    talos_version=$(yq eval '.talosVersion' "$TALENV")
    case "$(uname -m)" in
        aarch64|arm64) arch="arm64" ;;
        *)             arch="amd64" ;;
    esac
    echo "Downloading talosctl ${talos_version} (${arch})..."
    mkdir -p "$BIN_DIR"
    curl -fsSL "https://github.com/siderolabs/talos/releases/download/${talos_version}/talosctl-linux-${arch}" \
        -o "${BIN_DIR}/talosctl"
    chmod +x "${BIN_DIR}/talosctl"
    echo "Installed talosctl ${talos_version} (${arch}) to ${BIN_DIR}/talosctl"
}

# Get elizabeth (NAS) from dnsmasq
elizabeth_mac=$(get_mac_from_dnsmasq "elizabeth.lan")
elizabeth_ip=$(grep "host-record=elizabeth.lan" "$DNSMASQ_CONF" | cut -d',' -f2)

# Parse control plane and workers from talconfig
control_plane_nodes=""
worker_nodes=""

while IFS=',' read -r hostname ip mac is_cp; do
    entry="      - name: \"$hostname\"
        ip: \"$ip\"
        mac: \"$mac\"
        type: \"talos\""

    if [ "$is_cp" = "true" ]; then
        if [ -n "$control_plane_nodes" ]; then
            control_plane_nodes="$control_plane_nodes

$entry"
        else
            control_plane_nodes="$entry"
        fi
    else
        if [ -n "$worker_nodes" ]; then
            worker_nodes="$worker_nodes

$entry"
        else
            worker_nodes="$entry"
        fi
    fi
done < <(parse_talconfig)

# Format node sections: use [] for empty, or include the nodes
if [ -z "$control_plane_nodes" ]; then
    control_plane_section=" []"
else
    control_plane_section="
$control_plane_nodes"
fi

if [ -z "$worker_nodes" ]; then
    worker_section=" []"
else
    worker_section="
$worker_nodes"
fi

# Download talosctl
download_talosctl

# Generate config.yaml
cat > "$OUTPUT" << EOF
# Server groups configuration
# Servers are organized in priority groups
# Lower priority number = boots first
# Auto-generated by generate-config.sh from dnsmasq.conf and talconfig.yaml
server_groups:
  - name: "Storage (NAS)"
    priority: 1
    boot_delay_after_group: 120  # Wait 2 minutes after NAS before starting next group
    servers:
      - name: "elizabeth"
        ip: "$elizabeth_ip"
        mac: "$elizabeth_mac"
        type: "nas"

  - name: "Kubernetes Control Plane"
    priority: 2
    boot_delay_after_group: 90  # Wait 90 seconds before starting workers
    servers:${control_plane_section}

  - name: "Kubernetes Workers"
    priority: 3
    boot_delay_after_group: 0  # No delay after last group
    servers:${worker_section}

# UPS configuration (Network UPS Tools)
ups:
  host: "localhost"              # NUT runs on donkey (host networking)
  name: "ups"                   # UPS name in NUT configuration
  port: 3493                    # NUT port (default: 3493)
  username: "monuser"           # NUT monitor username
  min_charge: 50                # Minimum battery charge % before recovery

# Monitoring configuration
monitoring:
  check_interval: 300           # Full server ping sweep interval (300s)
  nut_poll_interval: 30         # NUT status polling in NORMAL state (30s)
  startup_delay: 180            # Wait 3 minutes after UPS is restored
  boot_delay_between_servers: 15  # Delay between servers in same group
  max_ups_wait: 3600            # Maximum time to wait for UPS (1 hour)
  ups_check_interval: 60        # Check UPS status every 60 seconds when waiting
  ping_timeout: 2               # Ping timeout in seconds
  wol_retry_count: 3            # Number of WOL packets to send per server
  wol_retry_delay: 1            # Delay between WOL packet retries
  grace_period_duration: 60     # How long to verify after quick OB->OL (60s)
  shutdown_wait_timeout: 600    # Max time waiting for all nodes to power off (600s)
  fsd_timer_duration: 120       # Must match NUT upssched ONBATT timer (120s)
  auto_wake_on_crash: false     # Auto-WOL servers that crash (no power event)

# Talos API configuration
talos:
  enabled: true
  talosctl_path: "/app/config/bin/talosctl"  # Downloaded by init container

# Network configuration
network:
  broadcast_ip: "192.168.1.255"  # Broadcast address for WOL packets
  wol_port: 9                    # Wake-on-LAN port (default: 9)

# Pushover notifications configuration
# Get your credentials from https://pushover.net/
pushover:
  enabled: true

  # Notification settings
  priority: 0           # -2=lowest, -1=low, 0=normal, 1=high, 2=emergency
  sound: "pushover"     # Sound: pushover, bike, bugle, cashregister, classical, cosmic, etc.

  # What events to notify about
  notify_on:
    servers_down: true          # When servers are found offline
    ups_not_ready: true         # When UPS is not ready for recovery
    recovery_started: true      # When recovery sequence starts
    recovery_completed: true    # When recovery is completed
    ups_restored: true          # When UPS returns to online status
    power_failure: true         # When UPS goes to battery
    shutdown_in_progress: true  # When nodes are shutting down
    all_nodes_off: true         # When all nodes confirmed powered off
    crash_detected: true        # When servers crash (no power event)
    errors: true                # On errors during monitoring
EOF

echo "Generated $OUTPUT"
