#!/bin/bash
set -euo pipefail

# Paths inside the init container
DNSMASQ_CONF="/work/dnsmasq/dnsmasq.conf"
TALCONFIG="/work/talos/talconfig.yaml"
OUTPUT="/work/power-nap-over/config.yaml"

# Function to get MAC address from dnsmasq.conf for a given hostname
get_mac_from_dnsmasq() {
    local hostname="$1"
    grep "dhcp-host=.*${hostname}" "$DNSMASQ_CONF" | head -1 | cut -d',' -f1 | cut -d'=' -f2
}

# Parse talconfig.yaml to extract nodes
# Returns: hostname,ip,mac,controlPlane (true/false)
parse_talconfig() {
    yq eval '.nodes[] | [.hostname, .ipAddress, .networkInterfaces[0].deviceSelector.hardwareAddr, .controlPlane] | @csv' "$TALCONFIG" | tr -d '"'
}

# Get elizabeth (NAS) from dnsmasq
elizabeth_mac=$(get_mac_from_dnsmasq "elizabeth.lan")
elizabeth_ip=$(grep "host-record=elizabeth.lan" "$DNSMASQ_CONF" | cut -d',' -f2)

# Parse control plane and workers from talconfig
control_plane_nodes=""
worker_nodes=""

while IFS=',' read -r hostname ip mac is_cp; do
    entry="      - name: \"$hostname\"
        ip: \"$ip\"
        mac: \"$mac\""

    if [ "$is_cp" = "true" ]; then
        if [ -n "$control_plane_nodes" ]; then
            control_plane_nodes="$control_plane_nodes

$entry"
        else
            control_plane_nodes="$entry"
        fi
    else
        if [ -n "$worker_nodes" ]; then
            worker_nodes="$worker_nodes

$entry"
        else
            worker_nodes="$entry"
        fi
    fi
done < <(parse_talconfig)

# Format node sections: use [] for empty, or include the nodes
if [ -z "$control_plane_nodes" ]; then
    control_plane_section=" []"
else
    control_plane_section="
$control_plane_nodes"
fi

if [ -z "$worker_nodes" ]; then
    worker_section=" []"
else
    worker_section="
$worker_nodes"
fi

# Generate config.yaml
cat > "$OUTPUT" << EOF
# Server groups configuration
# Servers are organized in priority groups
# Lower priority number = boots first
# Auto-generated by generate-config.sh from dnsmasq.conf and talconfig.yaml
server_groups:
  - name: "Storage (NAS)"
    priority: 1
    boot_delay_after_group: 120  # Wait 2 minutes after NAS before starting next group
    servers:
      - name: "elizabeth"
        ip: "$elizabeth_ip"
        mac: "$elizabeth_mac"

  - name: "Kubernetes Control Plane"
    priority: 2
    boot_delay_after_group: 90  # Wait 90 seconds before starting workers
    servers:${control_plane_section}

  - name: "Kubernetes Workers"
    priority: 3
    boot_delay_after_group: 0  # No delay after last group
    servers:${worker_section}

# UPS configuration (Network UPS Tools)
ups:
  host: "nut-server-room.lan"   # NUT server IP address
  name: "ups"                   # UPS name in NUT configuration
  port: 3493                    # NUT port (default: 3493)
  username: "monuser"           # NUT monitor username
  min_charge: 50                # Minimum battery charge % before recovery

# Monitoring configuration
monitoring:
  check_interval: 300           # Check servers every 5 minutes (300s)
  startup_delay: 180            # Wait 3 minutes after UPS is restored
  boot_delay_between_servers: 15  # Delay between servers in same group
  max_ups_wait: 3600            # Maximum time to wait for UPS (1 hour)
  ups_check_interval: 60        # Check UPS status every 60 seconds when waiting
  ping_timeout: 2               # Ping timeout in seconds
  wol_retry_count: 3            # Number of WOL packets to send per server
  wol_retry_delay: 1            # Delay between WOL packet retries

# Network configuration
network:
  broadcast_ip: "192.168.1.255"  # Broadcast address for WOL packets
  wol_port: 9                    # Wake-on-LAN port (default: 9)

# Pushover notifications configuration
# Get your credentials from https://pushover.net/
pushover:
  enabled: true

  # Notification settings
  priority: 0           # -2=lowest, -1=low, 0=normal, 1=high, 2=emergency
  sound: "pushover"     # Sound: pushover, bike, bugle, cashregister, classical, cosmic, etc.

  # What events to notify about
  notify_on:
    servers_down: true          # When servers are found offline
    ups_not_ready: true         # When UPS is not ready for recovery
    recovery_started: true      # When recovery sequence starts
    recovery_completed: true    # When recovery is completed
    ups_restored: true          # When UPS returns to online status
    errors: true                # On errors during monitoring
EOF

echo "Generated $OUTPUT"
