---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: headlamp-oidc
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: headlamp
        OIDC_CLIENT_SECRET: "{{ .headlamp }}"
        OIDC_ISSUER_URL: "https://auth.${DOMAIN}/application/o/headlamp/"
        OIDC_SCOPES: "openid,profile,email,groups,offline_access"
        OIDC_CALLBACK_URL: "https://gitops.${DOMAIN}/oidc-callback"
  dataFrom:
    - extract:
        key: oidc-client-secrets
